import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { verifyJWT } from '@/lib/auth/jwt'
import { z } from 'zod'

// Validation schema for creating grocery event
const CreateGroceryEventSchema = z.object({
  class_name: z.string().min(2, 'שם כיתה חייב להכיל לפחות 2 תווים'),
  event_name: z.string().min(2, 'שם אירוע חייב להכיל לפחות 2 תווים'),
  event_date: z.string().optional().nullable(),
  event_time: z.string().optional().nullable(),
  event_address: z.string().optional().nullable(),
  creator_name: z.string().optional().nullable(),
  creator_phone: z.string().regex(/^05\d{8}$/, 'מספר טלפון לא תקין').optional().nullable()
})

/**
 * GET /api/grocery
 * List all grocery events (admin only)
 */
export async function GET(req: NextRequest) {
  try {
    // Verify admin authentication
    const token = req.cookies.get('auth-token')
    if (!token || !(await verifyJWT(token.value))) {
      return NextResponse.json(
        { success: false, error: 'נדרשת הרשאת מנהל' },
        { status: 401 }
      )
    }

    const supabase = await createClient()
    const { searchParams } = new URL(req.url)
    const status = searchParams.get('status') || 'active'
    const limit = Math.min(parseInt(searchParams.get('limit') || '50'), 100)

    let query = supabase
      .from('grocery_events')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(limit)

    if (status !== 'all') {
      query = query.eq('status', status)
    }

    const { data, error } = await query

    if (error) {
      console.error('Grocery events query error:', error)
      return NextResponse.json(
        { success: false, error: 'שגיאה בטעינת רשימות הקניות' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      data: data || [],
      count: data?.length || 0
    })
  } catch (error) {
    console.error('Grocery events GET error:', error)
    return NextResponse.json(
      { success: false, error: 'שגיאה בטעינת רשימות הקניות' },
      { status: 500 }
    )
  }
}

/**
 * POST /api/grocery
 * Create a new grocery event (public - no auth required)
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const validation = CreateGroceryEventSchema.safeParse(body)

    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: 'נתונים לא תקינים',
          details: validation.error.errors.map(err => `${err.path.join('.')}: ${err.message}`)
        },
        { status: 400 }
      )
    }

    const supabase = await createClient()

    // Create the grocery event (share_token is auto-generated by DB trigger)
    const { data, error } = await supabase
      .from('grocery_events')
      .insert([{
        class_name: validation.data.class_name,
        event_name: validation.data.event_name,
        event_date: validation.data.event_date || null,
        event_time: validation.data.event_time || null,
        event_address: validation.data.event_address || null,
        creator_name: validation.data.creator_name || null,
        creator_phone: validation.data.creator_phone || null,
        status: 'active'
      }])
      .select()
      .single()

    if (error) {
      console.error('Grocery event creation error:', error)
      return NextResponse.json(
        { success: false, error: 'שגיאה ביצירת רשימת הקניות' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      data,
      share_url: `/grocery/${data.share_token}`,
      message: 'רשימת הקניות נוצרה בהצלחה'
    })
  } catch (error) {
    console.error('Grocery event POST error:', error)
    return NextResponse.json(
      { success: false, error: 'שגיאה ביצירת רשימת הקניות' },
      { status: 500 }
    )
  }
}
